config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :styles

      resources :interview_styles

      resources :job_categories

      resources :categories

      resources :interviews

      resources :users

      resources :job_applications

      resources :companies
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "companies#index"
  resources :styles
  resources :interview_styles
  resources :job_categories
  resources :categories
  resources :interviews
  resources :users
  resources :job_applications
  resources :companies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/job_category.rb
class JobCategory < ApplicationRecord
  # Direct associations

  belongs_to :category

  belongs_to :job_application

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    category.to_s
  end
end

app/controllers/api/v1/job_categories_controller.rb
class Api::V1::JobCategoriesController < Api::V1::GraphitiController
  def index
    job_categories = JobCategoryResource.all(params)
    respond_with(job_categories)
  end

  def show
    job_category = JobCategoryResource.find(params)
    respond_with(job_category)
  end

  def create
    job_category = JobCategoryResource.build(params)

    if job_category.save
      render jsonapi: job_category, status: :created
    else
      render jsonapi_errors: job_category
    end
  end

  def update
    job_category = JobCategoryResource.find(params)

    if job_category.update_attributes
      render jsonapi: job_category
    else
      render jsonapi_errors: job_category
    end
  end

  def destroy
    job_category = JobCategoryResource.find(params)

    if job_category.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: job_category
    end
  end
end

app/controllers/job_categories_controller.rb
class JobCategoriesController < ApplicationController
  before_action :set_job_category, only: %i[show edit update destroy]

  def index
    @q = JobCategory.ransack(params[:q])
    @job_categories = @q.result(distinct: true).includes(:job_application,
                                                         :category).page(params[:page]).per(10)
  end

  def show; end

  def new
    @job_category = JobCategory.new
  end

  def edit; end

  def create
    @job_category = JobCategory.new(job_category_params)

    if @job_category.save
      message = "JobCategory was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @job_category, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @job_category.update(job_category_params)
      redirect_to @job_category,
                  notice: "Job category was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @job_category.destroy
    message = "JobCategory was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to job_categories_url, notice: message
    end
  end

  private

  def set_job_category
    @job_category = JobCategory.find(params[:id])
  end

  def job_category_params
    params.require(:job_category).permit(:category_id, :job_application_id)
  end
end

app/views/job_categories/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Job Category #<%= job_category.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Category</dt>
      <dd>
        <% if @job_category.category.present? %>
          <%= link_to job_category.category, job_category.category %>
        <% end %>
      </dd>

      <dt>Job application</dt>
      <dd>
        <% if @job_category.job_application.present? %>
          <%= link_to job_category.job_application, job_category.job_application %>
        <% end %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back job_category, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_job_category_url(job_category), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to job_category, method: :delete, data: { confirm: "Do you really want to delete this job_category?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(job_category.updated_at) %> ago
  </div>
</div>

app/views/job_categories/_form.html.erb
<% was_validated = job_category.errors.any? %>

<%= form_with(model: job_category, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% category_class = "form-control" %>
    <% category_was_invalid = job_category.errors.include?(:category) %>

    <% if was_validated %>
      <% if category_was_invalid %>
        <% category_class << " is-invalid" %>
      <% else %>
        <% category_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.all, :id, :to_s, {}, class: "form-control" %>
    <% if category_was_invalid %>
      <% job_category.errors.full_messages_for(:category).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% job_application_class = "form-control" %>
    <% job_application_was_invalid = job_category.errors.include?(:job_application) %>

    <% if was_validated %>
      <% if job_application_was_invalid %>
        <% job_application_class << " is-invalid" %>
      <% else %>
        <% job_application_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :job_application_id %>
    <%= f.collection_select :job_application_id, JobApplication.all, :id, :to_s, {}, class: "form-control" %>
    <% if job_application_was_invalid %>
      <% job_category.errors.full_messages_for(:job_application).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/job_categories/_job_categories_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "job_categories_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :job_application_name_cont, "Job application name contains" %>
    <%= f.text_field :job_application_name_cont, :class => "form-control", :placeholder => "Job application name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :category_name_cont, "Category name contains" %>
    <%= f.text_field :category_name_cont, :class => "form-control", :placeholder => "Category name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/job_categories" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#job_categories_filters">
  Show filters
</a>

app/views/job_categories/_list_item.html.erb
<%= link_to job_category, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= job_category %>
    <small class="text-muted">
      <%= time_ago_in_words(job_category.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/job_categories/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Job Category #<%= @job_category.id %>
      </h2>

      <div class="card-body">
        <%= render "form", job_category: @job_category %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/job_categories/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Job Categories

      <%= link_to new_job_category_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "job_categories/job_categories_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Job Categories

        <%= link_to new_job_category_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @job_categories, partial: "list_item", as: :job_category %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @job_categories, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/job_categories/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Job Category
      </h2>

      <div class="card-body">
        <%= render "form", job_category: @job_category %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/job_categories/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @job_category, partial: "card", as: :job_category %>
  </div>
</div>