config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :styles

      resources :interview_styles

      resources :job_categories

      resources :categories

      resources :interviews

      resources :users

      resources :job_applications

      resources :companies
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "companies#index"
  resources :styles
  resources :interview_styles
  resources :job_categories
  resources :categories
  resources :interviews
  resources :users
  resources :job_applications
  resources :companies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/style.rb
class Style < ApplicationRecord
  # Direct associations

  has_many   :interview_styles,
             dependent: :destroy

  # Indirect associations

  has_many   :interviews,
             through: :interview_styles,
             source: :interview

  # Validations

  # Scopes

  def to_s
    name
  end
end

app/controllers/api/v1/styles_controller.rb
class Api::V1::StylesController < Api::V1::GraphitiController
  def index
    styles = StyleResource.all(params)
    respond_with(styles)
  end

  def show
    style = StyleResource.find(params)
    respond_with(style)
  end

  def create
    style = StyleResource.build(params)

    if style.save
      render jsonapi: style, status: :created
    else
      render jsonapi_errors: style
    end
  end

  def update
    style = StyleResource.find(params)

    if style.update_attributes
      render jsonapi: style
    else
      render jsonapi_errors: style
    end
  end

  def destroy
    style = StyleResource.find(params)

    if style.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: style
    end
  end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :set_style, only: %i[show edit update destroy]

  def index
    @q = Style.ransack(params[:q])
    @styles = @q.result(distinct: true).includes(:interview_styles,
                                                 :interviews).page(params[:page]).per(10)
  end

  def show
    @interview_style = InterviewStyle.new
  end

  def new
    @style = Style.new
  end

  def edit; end

  def create
    @style = Style.new(style_params)

    if @style.save
      redirect_to @style, notice: "Style was successfully created."
    else
      render :new
    end
  end

  def update
    if @style.update(style_params)
      redirect_to @style, notice: "Style was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @style.destroy
    redirect_to styles_url, notice: "Style was successfully destroyed."
  end

  private

  def set_style
    @style = Style.find(params[:id])
  end

  def style_params
    params.require(:style).permit(:name)
  end
end

app/views/styles/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Style #<%= style.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= style.name %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back style, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_style_url(style), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to style, method: :delete, data: { confirm: "Do you really want to delete this style?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(style.updated_at) %> ago
  </div>
</div>

app/views/styles/_form.html.erb
<% was_validated = style.errors.any? %>

<%= form_with(model: style, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = style.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% style.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/styles/_list_item.html.erb
<%= link_to style, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= style %>
    <small class="text-muted">
      <%= time_ago_in_words(style.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/styles/_style_interview_styles.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Interview Styles

    <a data-toggle="collapse" href="#style_interview_styles_new_form">
      Add interview style
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @style.interview_styles.each do |interview_style| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to interview_style, interview_style %>

        <%= link_to interview_style, method: :delete, data: { confirm: "Do you really want to delete this interview_style" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="style_interview_styles_new_form">
        <%= render partial: "styles/style_interview_styles_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/styles/_style_interview_styles_new_form.html.erb
<%= form_with(model: @interview_style, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :interview_id %>

    <%= f.collection_select :interview_id, Interview.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :style_id, value: @style.id %>

  <%= f.submit "Create interview style", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/styles/_style_interviews.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Interviews
  </div>

  <ul class="list-group list-group-flush">
    <% @style.interviews.each do |interview| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/interviews/<%= interview.id %>">
          <%= interview %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/styles/_styles_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "styles_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>




  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/styles" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#styles_filters">
  Show filters
</a>

app/views/styles/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Style #<%= @style.id %>
      </h2>

      <div class="card-body">
        <%= render "form", style: @style %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/styles/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Styles

      <%= link_to new_style_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "styles/styles_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Styles

        <%= link_to new_style_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @styles, partial: "list_item", as: :style %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @styles, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/styles/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Style
      </h2>

      <div class="card-body">
        <%= render "form", style: @style %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/styles/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @style, partial: "card", as: :style %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "styles/style_interview_styles" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "styles/style_interviews" %>
  </div>
</div>