config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :styles

      resources :interview_styles

      resources :job_categories

      resources :categories

      resources :interviews

      resources :users

      resources :job_applications

      resources :companies
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "companies#index"
  resources :styles
  resources :interview_styles
  resources :job_categories
  resources :categories
  resources :interviews
  resources :users
  resources :job_applications
  resources :companies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  # Direct associations

  has_many   :roles,
             class_name: "JobApplication",
             dependent: :destroy

  # Indirect associations

  # Validations

  validates :name, presence: true

  # Scopes

  def to_s
    name
  end
end

app/controllers/api/v1/companies_controller.rb
class Api::V1::CompaniesController < Api::V1::GraphitiController
  def index
    companies = CompanyResource.all(params)
    respond_with(companies)
  end

  def show
    company = CompanyResource.find(params)
    respond_with(company)
  end

  def create
    company = CompanyResource.build(params)

    if company.save
      render jsonapi: company, status: :created
    else
      render jsonapi_errors: company
    end
  end

  def update
    company = CompanyResource.find(params)

    if company.update_attributes
      render jsonapi: company
    else
      render jsonapi_errors: company
    end
  end

  def destroy
    company = CompanyResource.find(params)

    if company.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: company
    end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[show edit update destroy]

  def index
    @q = Company.ransack(params[:q])
    @companies = @q.result(distinct: true).includes(:roles).page(params[:page]).per(10)
  end

  def show
    @job_application = JobApplication.new
  end

  def new
    @company = Company.new
  end

  def edit; end

  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to @company, notice: "Company was successfully created."
    else
      render :new
    end
  end

  def update
    if @company.update(company_params)
      redirect_to @company, notice: "Company was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @company.destroy
    redirect_to companies_url, notice: "Company was successfully destroyed."
  end

  private

  def set_company
    @company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(:name, :industry, :size)
  end
end

app/views/companies/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Company #<%= company.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= company.name %></dd>

      <dt>Industry</dt>
      <dd><%= company.industry %></dd>

      <dt>Size</dt>
      <dd><%= company.size %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back company, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_company_url(company), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to company, method: :delete, data: { confirm: "Do you really want to delete this company?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(company.updated_at) %> ago
  </div>
</div>

app/views/companies/_companies_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "companies_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :size_cont, "Size contains" %>
    <%= f.text_field :size_cont, :class => "form-control", :placeholder => "Size contains" %>
  </div>

  <div class="form-group">
    <%= f.label :industry_cont, "Industry contains" %>
    <%= f.text_field :industry_cont, :class => "form-control", :placeholder => "Industry contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :roles_name_cont, "Roles name contains" %>
    <%= f.text_field :roles_name_cont, :class => "form-control", :placeholder => "Roles name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/companies" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#companies_filters">
  Show filters
</a>

app/views/companies/_company_roles.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Roles

    <a data-toggle="collapse" href="#company_roles_new_form">
      Add job application
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @company.roles.each do |job_application| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to job_application, job_application %>

        <%= link_to job_application, method: :delete, data: { confirm: "Do you really want to delete this job_application" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="company_roles_new_form">
        <%= render partial: "companies/company_roles_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/companies/_company_roles_new_form.html.erb
<%= form_with(model: @job_application, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :name %>

    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, rows: "3", class: "form-control" %>
  </div>

  <%= f.hidden_field :company_id, value: @company.id %>

  <div class="form-group">
    <%= f.label :interest_level %>

    <%= f.text_field :interest_level, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :platform %>

    <%= f.text_field :platform, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :networking %>

    <%= f.text_field :networking, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :comments %>
    <%= f.text_area :comments, rows: "3", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :applied_on %>

    <%= f.date_select :applied_on, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :heard_back_on %>
    <%= f.datetime_select :heard_back_on, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :user_id %>

    <%= f.collection_select :user_id, User.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :job_type_id %>

    <%= f.text_field :job_type_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :url %>

    <%= f.text_field :url, class: "form-control" %>
  </div>

  <%= f.submit "Create job application", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/companies/_form.html.erb
<% was_validated = company.errors.any? %>

<%= form_with(model: company, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = company.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% company.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% industry_class = "form-control" %>
    <% industry_was_invalid = company.errors.include?(:industry) %>

    <% if was_validated %>
      <% if industry_was_invalid %>
        <% industry_class << " is-invalid" %>
      <% else %>
        <% industry_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :industry %>
    <%= f.text_field :industry, class: industry_class, placeholder: "Enter industry" %>
    <% if industry_was_invalid %>
      <% company.errors.full_messages_for(:industry).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% size_class = "form-control" %>
    <% size_was_invalid = company.errors.include?(:size) %>

    <% if was_validated %>
      <% if size_was_invalid %>
        <% size_class << " is-invalid" %>
      <% else %>
        <% size_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :size %>
    <%= f.text_field :size, class: size_class, placeholder: "Enter size" %>
    <% if size_was_invalid %>
      <% company.errors.full_messages_for(:size).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/companies/_list_item.html.erb
<%= link_to company, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= company %>
    <small class="text-muted">
      <%= time_ago_in_words(company.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/companies/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Company #<%= @company.id %>
      </h2>

      <div class="card-body">
        <%= render "form", company: @company %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/companies/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Companies

      <%= link_to new_company_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "companies/companies_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Companies

        <%= link_to new_company_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @companies, partial: "list_item", as: :company %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @companies, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/companies/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Company
      </h2>

      <div class="card-body">
        <%= render "form", company: @company %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/companies/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @company, partial: "card", as: :company %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "companies/company_roles" %>
  </div>
</div>