config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :styles

      resources :interview_styles

      resources :job_categories

      resources :categories

      resources :interviews

      resources :users

      resources :job_applications

      resources :companies
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "companies#index"
  resources :styles
  resources :interview_styles
  resources :job_categories
  resources :categories
  resources :interviews
  resources :users
  resources :job_applications
  resources :companies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  # Direct associations

  has_many   :job_categories,
             dependent: :destroy

  # Indirect associations

  has_many   :job_applications,
             through: :job_categories,
             source: :job_application

  # Validations

  # Scopes

  def to_s
    name
  end
end

app/controllers/api/v1/categories_controller.rb
class Api::V1::CategoriesController < Api::V1::GraphitiController
  def index
    categories = CategoryResource.all(params)
    respond_with(categories)
  end

  def show
    category = CategoryResource.find(params)
    respond_with(category)
  end

  def create
    category = CategoryResource.build(params)

    if category.save
      render jsonapi: category, status: :created
    else
      render jsonapi_errors: category
    end
  end

  def update
    category = CategoryResource.find(params)

    if category.update_attributes
      render jsonapi: category
    else
      render jsonapi_errors: category
    end
  end

  def destroy
    category = CategoryResource.find(params)

    if category.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: category
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @q = Category.ransack(params[:q])
    @categories = @q.result(distinct: true).includes(:job_categories,
                                                     :job_applications).page(params[:page]).per(10)
  end

  def show
    @job_category = JobCategory.new
  end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: "Category was successfully created."
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: "Category was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url, notice: "Category was successfully destroyed."
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/views/categories/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Category #<%= category.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= category.name %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back category, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_category_url(category), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to category, method: :delete, data: { confirm: "Do you really want to delete this category?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(category.updated_at) %> ago
  </div>
</div>

app/views/categories/_categories_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "categories_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :job_applications_name_cont, "Job applications name contains" %>
    <%= f.text_field :job_applications_name_cont, :class => "form-control", :placeholder => "Job applications name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/categories" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#categories_filters">
  Show filters
</a>

app/views/categories/_category_job_applications.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Job Applications
  </div>

  <ul class="list-group list-group-flush">
    <% @category.job_applications.each do |job_application| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/job_applications/<%= job_application.id %>">
          <%= job_application %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/categories/_category_job_categories.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Job Categories

    <a data-toggle="collapse" href="#category_job_categories_new_form">
      Add job category
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @category.job_categories.each do |job_category| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to job_category, job_category %>

        <%= link_to job_category, method: :delete, data: { confirm: "Do you really want to delete this job_category" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="category_job_categories_new_form">
        <%= render partial: "categories/category_job_categories_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/categories/_category_job_categories_new_form.html.erb
<%= form_with(model: @job_category, local: true) do |f| %>

  <%= f.hidden_field :category_id, value: @category.id %>

  <div class="form-group">
    <%= f.label :job_application_id %>

    <%= f.collection_select :job_application_id, JobApplication.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.submit "Create job category", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/categories/_form.html.erb
<% was_validated = category.errors.any? %>

<%= form_with(model: category, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = category.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% category.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/categories/_list_item.html.erb
<%= link_to category, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= category %>
    <small class="text-muted">
      <%= time_ago_in_words(category.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/categories/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Category #<%= @category.id %>
      </h2>

      <div class="card-body">
        <%= render "form", category: @category %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Categories

      <%= link_to new_category_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "categories/categories_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Categories

        <%= link_to new_category_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @categories, partial: "list_item", as: :category %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @categories, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Category
      </h2>

      <div class="card-body">
        <%= render "form", category: @category %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @category, partial: "card", as: :category %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "categories/category_job_categories" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "categories/category_job_applications" %>
  </div>
</div>